version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/careerpulse
      - JWT_SECRET=super_secret_key_change_in_production
      - ENVIRONMENT=production
    volumes:
      - ./backend/dataset:/app/backend/dataset
      - ./backend/ml/trained_models:/app/backend/ml/trained_models
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=https://ai-powered-resume-filter-and-career.onrender.com
    depends_on:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
